#################################
########## AdiAuth ##############
############### -by ad1tya2 #####

#Dont touch At any cost
configversion: 2

#storage
#Options available, h2 and mysql
#H2 is also a local storage system, no external database is needed
#h2 is a good alternative to sqlite
database: h2

#database settings for mysql if it is enabled
mysql:
  username: username
  password: passmyword
  database: datatomybasetothebase
  host: localhost

# If the name of a cracked account becomes premium, it converts the account as well
# The uuid will remain cracked when checked inside the server
# But the player will be automatically logged in as cracked
# There is a risk factor ofcourse, But the chances are that this only happens when a person with a cracked account buys a new premium account
# It is less likely that a person buys an account with the same username as a cracked guy
convertOldCrackedToPremium: true

#The tme to keep a player logged in for in Minutes
#So that they don't have to login everytime they reconnect
#Note that the session will be reset when they join from a new ip
sessionTime: 120


#The servers where they will be teleported to login
authServers:
  - hub

#The servers where players will be sent to after logging in
lobbyServers:
  - hub

#The url of a backup server to use, Contact me on my discord if you wish to use it
#Note: I dont give backup server for free xD
backupServer: ''

#Use the backup server always
forceBackupServer: false

#Give darkness effect to players who haven't logged in
#If you want to reload this then you will need to reload this on bungee and restart the backend spigot server
blindness: true

#Prevent players who haven't logged in from moving
#If you want to reload this then you will need to reload this on bungee and restart the backend spigot server
freezePlayers: true

#The interval in seconds to check if a server is online or not
serverCheckInterval: 10

#Commands that can be executed without being logged in
whitelistedCommands:
  - /register
  - /reg
  - /login
  - /l

#The maximum number of premium accounts that can join from a single ip
maxPremiumAccounts: 3

#The maximum number of cracked accounts that can be created by a single ip
maxCrackedAccounts: 2

#The maximum number of accounts that can be created in total by a single ip
#If maxPremiumAccounts is 2
# and maxCrackedAccounts is 2
# But if maxTotalAccounts is 3
# Then only the first 3 accounts will be allowed
maxTotalAccounts: 3

#The message to show when a cracked person with a premium name tries to login for the second time
#Leave empty if you dont want this feature to be enabled
secondAttempt: '&4&lERROR! &cThis username is already taken by a premium player. Change your username to something uncommon.'

#Whether to disconnect the player if he enters the wrong password
disconnectOnWrongPass: true

#The time in seconds that the players have to login or register
authTime: 120

messages:
  registerMessage: '&e&lWelcome! &ePlease use /register <password> to play.'
  loginMessage: '&e&lWelcome! &ePlease use /login <password> to play.'
  registerTitle: '&e/register <password>'
  loginTitle: '&e/login <password>'
  registerError: '&4&lInvalid format! &cUse /register <password>.'
  alreadyRegistered: '&8&lYou have already registered. &7Please use /changepass <old password> <new password> if you want to change your password.'
  # loginAndRegisterSuccess: '&r &9⁂&b⁂ &e&lWelcome to YourServer Have fun! &9⁂&b⁂' - This also works.
  loginAndRegisterSuccess: |-
    &r   &9⁂&b⁂ &6&lWelcome to YourServer and have fun! &9⁂&b⁂
    &r                    &eThanks for using AdiAuth!
    &r       &eLeave a review at Spigot to further support us.
    &r   &ehttps://www.spigotmc.org/resources/adiauth.95828/
  loginAndRegisterSuccessTitle: '&a&l✓'
  alreadyLoggedIn: '&8&lYou are already logged in!&7 You dont need to use this command.'
  loginError: '&4&lInvalid format! &cUse /login <password>.'
  loginNotRegistered: '&cYou need to register first to do this!'
  loginWrongPass: '&4&lERROR! &cYou have used an incorrect password!'
  noServersAvailable: '&4&lERROR! &cNo servers are currently available to connect you to, please come back later.'
  logoutMessage: '&a&l Successfully logged out!'
  changePassError: '&4&lInvalid format!&c Please use /changepass <old password> <new password>.'
  successfulChangePass: '&aPassword changed successfully!'
  genericPremiumError: '&e You dont need to use this command. Premium accounts are secured even without registering in our server.'
  tooManyAccounts: '&4&lERROR! &cThere are too many accounts from this IP.'
  # TIMELEFT will be replaced by number of seconds left.
  loginRegisterBossBar: '&c✘ &eYou have TIMELEFT seconds. &c✘'
  authTimeExceeded: '&4&lERROR! &cYou were not able to login within the given time!'
